# -*- coding: utf-8 -*-
"""ML-Task01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CUKrm3CirhLizPzYKOdjiXwjjuIs7wvu
"""

#Prodigy-ML-01

#Implement a linear regression model to predict the prices of houses based on their square footage and the number of bedrooms and bathrooms.

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Load the dataset
train_data = pd.read_csv('train.csv')

# Display the first few rows to understand the structure
print(train_data.head())

# Select relevant features and target variable
features = ['GrLivArea', 'BedroomAbvGr', 'FullBath']
target = 'SalePrice'

# Extract features and target variable
X = train_data[features]
y = train_data[target]

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a linear regression model
model = LinearRegression()

# Fit the model on the training data
model.fit(X_train, y_train)

# Predict on the test data
y_pred = model.predict(X_test)

# Calculate Mean Squared Error (MSE) and R-squared
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

# Example prediction
new_data = pd.DataFrame([[2000, 3, 2]], columns=['GrLivArea', 'BedroomAbvGr', 'FullBath'])
predicted_price = model.predict(new_data)

print(f'Predicted price for the new house: ${predicted_price[0]}')

#Crafted With Love by Sam Naveenkumar .V